export const CONTENT_ERROR_CODES = [
  'AUDIENCE_INPUT_INVALID',
  'AUDIENCE_STAGE_INVALID',
  'AUDIENCE_TASK_MISMATCH',
  'AUDIENCE_ORIGIN_MISSING',
  'AUDIENCE_UNCERTAINTY_MISSING',
  'AUDIENCE_TRANSITION_INVALID',
  'STRATEGY_SCHEMA_INVALID',
  'STRATEGY_TASK_MISMATCH',
  'STRATEGY_AUDIENCE_MISMATCH',
  'STRATEGY_GROUNDING_FAILED',
  'STRATEGY_LIMITS_OMITTED',
  'STRATEGY_GATE_BLOCKED',
  'STRATEGY_GATE_REVIEW_REQUIRED',
  'ARCHITECTURE_SCHEMA_INVALID',
  'ARCHITECTURE_GATE_NOT_PROCEED',
  'ARCHITECTURE_TASK_MISMATCH',
  'ARCHITECTURE_STRATEGY_MISMATCH',
  'ARCHITECTURE_UNIT_ORDER_INVALID',
  'ARCHITECTURE_PROPOSITION_UNGROUNDED',
  'ARCHITECTURE_MATERIAL_STRATEGY_CHANGE',
  'CANDIDATE_SCHEMA_INVALID',
  'CANDIDATE_TASK_MISMATCH',
  'CANDIDATE_STRATEGY_MISMATCH',
  'CANDIDATE_ARCHITECTURE_MISMATCH',
  'CANDIDATE_PARENT_INVALID',
  'CANDIDATE_INHERITED_AUTHORITY',
  'RUN_CONFIG_MISMATCH',
  'GENERATION_OUTPUT_MALFORMED',
  'GENERATION_CONTEXT_STALE',
  'GENERATION_CONTEXT_UNATTRIBUTED',
  'GENERATION_CONTEXT_NOT_ALLOWED',
  'GENERATION_SECRET_EXPOSURE',
  'GENERATION_AUTHORITY_ESCALATION',
  'GENERATION_EXTERNAL_EFFECT_FORBIDDEN',
  'TENANT_SCOPE_VIOLATION',
  'MEANING_ASSUMPTION_PROMOTED',
  'MEANING_UNKNOWN_PROMOTED',
  'MEANING_HARD_RULE_WEAKENED',
  'CANONICAL_SERIALIZATION_INVALID',
  'RUNTIME_STAGE_OUTPUT_INVALID',
  'SPEC06_HANDOFF_INVALID',
] as const;

export type ContentErrorCode = (typeof CONTENT_ERROR_CODES)[number];

export class ContentDomainError extends Error {
  constructor(
    public readonly code: ContentErrorCode,
    message: string,
  ) {
    super(`[${code}] ${message}`);
    this.name = 'ContentDomainError';
  }
}

export function failContent(code: ContentErrorCode, message: string): never {
  throw new ContentDomainError(code, message);
}
